name: Github Pages

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Checkout GH pages
        uses: actions/checkout@v4
        with:
          repository: stellar/open-rpc-docs-react
          ref: gh-pages
          path: docs

      - name: Generate docs
        continue-on-error: true
        run: yarn build:docs

      - name: Publish docs
        run: |
          TAG=`git describe --tags`
          cd docs/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m $TAG
          git push origin gh-pages
